# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Cbiweight_radius <- function(grid_x, grid_y, input_x, input_y, input_val, radius, normalize) {
    .Call('_biweight_Cbiweight_radius', PACKAGE = 'biweight', grid_x, grid_y, input_x, input_y, input_val, radius, normalize)
}

Cbiweight <- function(grid_x, grid_y, input_x, input_y, input_val, radius, normalize) {
    .Call('_biweight_Cbiweight', PACKAGE = 'biweight', grid_x, grid_y, input_x, input_y, input_val, radius, normalize)
}

