# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Cbiweight <- function(input, grid, value, radius, normalize) {
    .Call('_biweight_Cbiweight', PACKAGE = 'biweight', input, grid, value, radius, normalize)
}

